/**
 * NEXORA catalogue — the demo dataset the storefront and dashboard ship with.
 * Prices are in INR. `colorway` drives the generated product visual on the
 * client, so no binary assets are required to render the catalogue.
 */
export const catalog = [
  {
    sku: 'NX-AUD-PX1',
    images: ['https://images.unsplash.com/photo-1553774661-0651f14b2da4?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Pulse X1', category: 'Audio', colorway: '#1B39C9',
    tagline: 'Wireless ANC headphones with 40h playback',
    price: 7999, compareAtPrice: 10999, cost: 4100, stock: 42, rating: 4.7, unitsSold: 412, isFeatured: true,
    description: 'The Pulse X1 pairs a 40mm titanium-coated driver with adaptive noise cancellation that samples your surroundings 600 times a second. Memory-foam earcups and a 248g frame keep it comfortable through long flights, and a 10-minute charge returns six hours of listening.',
    highlights: ['Adaptive ANC with transparency mode', '40 hours playback, 6 hours from a 10-min charge', 'Multipoint pairing across two devices', 'Bluetooth 5.3 with LDAC'],
    specs: { Driver: '40mm titanium-coated', Battery: '40 hours (ANC on)', Weight: '248 g', Connectivity: 'Bluetooth 5.3, USB-C, 3.5mm', Codecs: 'SBC, AAC, LDAC' },
    tags: ['headphones', 'anc', 'over-ear', 'travel'],
  },
  {
    sku: 'NX-AUD-PA2',
    images: ['https://images.unsplash.com/photo-1621451766686-38d3f8964a0f?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1638803782506-d975a6809f43?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Pulse Air 2', category: 'Audio', colorway: '#0E7A5F',
    tagline: 'True wireless earbuds with hybrid ANC',
    price: 4499, compareAtPrice: 5999, cost: 2050, stock: 86, rating: 4.5, unitsSold: 738, isFeatured: true,
    description: 'Pulse Air 2 fits six hours of playback into a 4.1g bud. Hybrid ANC cuts cabin and traffic noise, while four beam-forming mics keep calls clear in the wind. The case adds three full charges and supports wireless charging.',
    highlights: ['Hybrid ANC, up to 32dB reduction', '6h per bud, 24h with the case', 'IPX5 sweat and splash resistance', 'Wear detection auto-pause'],
    specs: { Driver: '11mm dynamic', Battery: '6h bud / 24h case', 'Water resistance': 'IPX5', Connectivity: 'Bluetooth 5.3', Charging: 'USB-C, Qi wireless' },
    tags: ['earbuds', 'tws', 'anc'],
  },
  {
    sku: 'NX-AUD-SB3',
    images: ['https://images.unsplash.com/photo-1616750819287-955503f65d42?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1624978960894-bed9218acd39?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Sonar 3 Speaker', category: 'Audio', colorway: '#B4532C',
    tagline: 'Portable 30W Bluetooth speaker, IP67',
    price: 5499, compareAtPrice: 6999, cost: 2600, stock: 34, rating: 4.6, unitsSold: 291,
    description: 'Two 15W drivers and a pair of passive radiators give the Sonar 3 a low end that belies its size. It survives a drop in the pool at IP67, runs 18 hours on a charge, and pairs with a second unit for stereo.',
    highlights: ['30W stereo output with passive radiators', 'IP67 dust and water protection', '18-hour battery with USB-C fast charge', 'Stereo pairing with a second Sonar'],
    specs: { Output: '30W RMS', Battery: '18 hours', Protection: 'IP67', Connectivity: 'Bluetooth 5.2, AUX', Weight: '690 g' },
    tags: ['speaker', 'bluetooth', 'outdoor'],
  },
  {
    sku: 'NX-AUD-ST1',
    images: ['https://images.unsplash.com/photo-1548378329-437e1ef34263?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1533379007656-3a10925da2e2?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Studio Monitor One', category: 'Audio', colorway: '#2C3140',
    tagline: 'Open-back reference headphones for mixing',
    price: 12999, compareAtPrice: 15999, cost: 7200, stock: 12, rating: 4.8, unitsSold: 96,
    description: 'A flat, uncoloured response tuned for mixing decisions rather than excitement. The open-back grille gives a wide stage, the 250-ohm drivers scale with a proper amp, and the velour pads are user-replaceable.',
    highlights: ['Flat reference tuning, ±3dB 15Hz–28kHz', 'Open-back 250-ohm drivers', 'Replaceable velour pads and cable', 'Detachable 3m coiled cable'],
    specs: { Impedance: '250 ohm', Response: '15Hz – 28kHz', Design: 'Open-back, circumaural', Weight: '295 g', Cable: 'Detachable 3m coiled' },
    tags: ['studio', 'monitoring', 'wired'],
  },
  {
    sku: 'NX-WEA-CH2',
    images: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Chrono 2', category: 'Wearables', colorway: '#1F2933',
    tagline: 'AMOLED smartwatch with 14-day battery',
    price: 9499, compareAtPrice: 12499, cost: 4800, stock: 51, rating: 4.6, unitsSold: 523, isFeatured: true,
    description: 'A 1.43" AMOLED panel at 466x466 under sapphire-hardened glass, wrapped in a 316L steel case. Dual-band GPS holds a lock under tree cover, and continuous SpO2 and heart-rate tracking still leave you two weeks between charges.',
    highlights: ['1.43" AMOLED, 466x466, 1000 nits', 'Dual-band GPS with offline maps', '14-day typical battery life', '5ATM water resistance'],
    specs: { Display: '1.43" AMOLED', Battery: '14 days typical', GPS: 'Dual-band L1 + L5', 'Water resistance': '5ATM', Case: '316L stainless steel' },
    tags: ['smartwatch', 'fitness', 'gps'],
  },
  {
    sku: 'NX-WEA-CL1',
    images: ['https://images.unsplash.com/photo-1624096104992-9b4fa3a279dd?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1617043983671-adaadcaa2460?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Chrono Lite', category: 'Wearables', colorway: '#7A5AF8',
    tagline: 'Everyday fitness watch with sleep staging',
    price: 4999, compareAtPrice: 6499, cost: 2200, stock: 73, rating: 4.3, unitsSold: 604,
    description: 'The Chrono Lite covers the essentials well: 120 workout modes, sleep staging with a morning readiness score, and a 1.32" display bright enough to read outdoors. At 32g it disappears overnight.',
    highlights: ['120 workout modes', 'Sleep staging and readiness score', '10-day battery life', '32g body, silicone quick-release strap'],
    specs: { Display: '1.32" TFT', Battery: '10 days', Sensors: 'HR, SpO2, accelerometer', Weight: '32 g', 'Water resistance': '3ATM' },
    tags: ['fitness-band', 'sleep', 'budget'],
  },
  {
    sku: 'NX-WEA-RG1',
    images: ['https://images.unsplash.com/photo-1632794716789-42d9995fb5b6?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1461141346587-763ab02bced9?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Halo Ring', category: 'Wearables', colorway: '#334155',
    tagline: 'Titanium sleep and recovery ring',
    price: 18999, cost: 9400, stock: 8, rating: 4.4, unitsSold: 61,
    description: 'Recovery tracking without a screen on your wrist. The Halo reads heart rate variability, skin temperature and movement through the night, then reports one number in the morning. Titanium shell, seven-day battery, no subscription.',
    highlights: ['HRV, skin temperature and sleep staging', '7-day battery, 80-minute full charge', 'Grade 5 titanium, 4.1g', 'No subscription required'],
    specs: { Material: 'Grade 5 titanium', Battery: '7 days', Weight: '4.1 g', Sizes: 'US 6 – 13', Charging: 'Magnetic dock' },
    tags: ['ring', 'sleep', 'recovery'],
  },
  {
    sku: 'NX-KEY-MK7',
    images: ['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Forge 75', category: 'Keyboards', colorway: '#B4762A',
    tagline: '75% hot-swap mechanical keyboard, gasket mount',
    price: 8999, compareAtPrice: 11499, cost: 4300, stock: 29, rating: 4.9, unitsSold: 318, isFeatured: true,
    description: 'A gasket-mounted 75% board with a CNC aluminium case, five layers of dampening and a sound profile closer to a custom build than an off-the-shelf keyboard. Hot-swap sockets take 3- and 5-pin switches; QMK/VIA remapping works out of the box.',
    highlights: ['Gasket-mounted CNC aluminium case', 'Hot-swap 3- and 5-pin sockets', 'QMK/VIA remapping, per-key RGB', 'Tri-mode: USB-C, Bluetooth, 2.4GHz'],
    specs: { Layout: '75% (82 keys)', Case: 'CNC aluminium', Switches: 'Nexora Amber tactile, pre-lubed', Connectivity: 'USB-C / BT 5.1 / 2.4GHz', Battery: '4000 mAh' },
    tags: ['mechanical', 'hot-swap', 'custom'],
  },
  {
    sku: 'NX-KEY-MK6',
    images: ['https://images.unsplash.com/photo-1595044426077-d36d9236d54a?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1632079003110-d694908500da?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Forge 65 Wireless', category: 'Keyboards', colorway: '#0F766E',
    tagline: 'Compact 65% board with tri-mode connectivity',
    price: 6499, compareAtPrice: 7999, cost: 3000, stock: 47, rating: 4.5, unitsSold: 387,
    description: 'The 65% layout keeps arrow keys without the numpad, freeing desk space for the mouse. PBT double-shot caps, pre-lubed linears and a 3000mAh battery that lasts a month with the backlight off.',
    highlights: ['65% layout with dedicated arrows', 'PBT double-shot keycaps', 'Pre-lubed linear switches', 'Up to 30 days on a charge'],
    specs: { Layout: '65% (68 keys)', Keycaps: 'PBT double-shot', Switches: 'Nexora Jade linear', Connectivity: 'USB-C / BT 5.1 / 2.4GHz', Battery: '3000 mAh' },
    tags: ['mechanical', 'compact', 'wireless'],
  },
  {
    sku: 'NX-KEY-KC1',
    images: ['https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1626958390898-162d3577f293?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Dye-Sub Keycap Set', category: 'Keyboards', colorway: '#475569',
    tagline: '142-key PBT cherry-profile keycap set',
    price: 3499, cost: 1400, stock: 64, rating: 4.4, unitsSold: 214,
    description: 'Cherry-profile PBT caps in a muted graphite and cream palette, dye-sublimated so the legends outlast the board. 142 keys cover 60% through full-size layouts including ISO and split-spacebar kits.',
    highlights: ['142 keys, covers 60% to full-size', 'Dye-sublimated legends', '1.5mm PBT walls', 'ISO and split-spacebar support'],
    specs: { Profile: 'Cherry', Material: 'PBT, 1.5mm', Keys: '142', Compatibility: 'MX-style stems', Finish: 'Matte' },
    tags: ['keycaps', 'pbt', 'accessories'],
  },
  {
    sku: 'NX-GAM-MS5',
    images: ['https://images.unsplash.com/photo-1605773527852-c546a8584ea3?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1616296425622-4560a2ad83de?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Vantage 5 Mouse', category: 'Gaming', colorway: '#C02B52',
    tagline: '58g wireless gaming mouse, 26K sensor',
    price: 5999, compareAtPrice: 7499, cost: 2700, stock: 38, rating: 4.7, unitsSold: 446, isFeatured: true,
    description: 'A 58g symmetrical shell over a 26,000 DPI optical sensor with a 1ms wireless polling rate. Optical switches rated to 90 million clicks remove the double-click failure that kills most mice, and 90 hours of battery means you charge it monthly.',
    highlights: ['58g shell, no honeycomb cutouts', '26,000 DPI optical sensor', 'Optical switches, 90M click rating', '90-hour battery, 1000Hz polling'],
    specs: { Weight: '58 g', Sensor: '26,000 DPI optical', Switches: 'Optical, 90M clicks', Polling: '1000 Hz', Battery: '90 hours' },
    tags: ['mouse', 'esports', 'lightweight'],
  },
  {
    sku: 'NX-GAM-HS4',
    images: ['https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1614149162883-504ce4d13909?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Arena Headset', category: 'Gaming', colorway: '#6D28D9',
    tagline: 'Low-latency wireless gaming headset',
    price: 7499, compareAtPrice: 8999, cost: 3500, stock: 26, rating: 4.4, unitsSold: 268,
    description: 'A 2.4GHz link at under 20ms latency, spatial audio tuned for footstep cues, and a detachable boom mic with a hardware mute. The suspension headband spreads weight so it stays comfortable across a long session.',
    highlights: ['2.4GHz wireless, sub-20ms latency', 'Spatial audio with footstep EQ preset', 'Detachable broadcast-grade boom mic', '30-hour battery'],
    specs: { Driver: '50mm neodymium', Battery: '30 hours', Latency: '<20 ms', Microphone: 'Detachable cardioid', Compatibility: 'PC, PS5, Switch' },
    tags: ['headset', 'gaming', 'wireless'],
  },
  {
    sku: 'NX-GAM-CT1',
    images: ['https://images.unsplash.com/photo-1696710257827-75e2e5954059?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1628832307345-7404b47f1751?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Arena Controller', category: 'Gaming', colorway: '#1E293B',
    tagline: 'Hall-effect controller with back paddles',
    price: 6299, cost: 2900, stock: 19, rating: 4.5, unitsSold: 173,
    description: 'Hall-effect sticks that do not drift, four remappable back paddles and trigger stops for shooters. Profiles are stored on the controller, so your layout follows you between a PC and a handheld.',
    highlights: ['Hall-effect sticks, drift-free', 'Four remappable back paddles', 'Two-stage trigger stops', 'Three onboard profiles'],
    specs: { Connectivity: 'USB-C / BT / 2.4GHz', Sticks: 'Hall-effect', Battery: '25 hours', Weight: '268 g', Compatibility: 'PC, Android, Switch' },
    tags: ['controller', 'hall-effect', 'gaming'],
  },
  {
    sku: 'NX-GAM-MP2',
    images: ['https://images.unsplash.com/photo-1632160871990-be30194885aa?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1629429408708-3a59f51979c5?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Glide XL Deskmat', category: 'Gaming', colorway: '#0F172A',
    tagline: '900x400mm stitched cloth desk mat',
    price: 1499, compareAtPrice: 1999, cost: 520, stock: 120, rating: 4.6, unitsSold: 812,
    description: 'A 900x400mm cloth surface over 4mm of natural rubber, with stitched edges that do not fray. The weave is tuned for a consistent glide on optical sensors and it rolls flat within an hour of unboxing.',
    highlights: ['900 x 400 x 4 mm', 'Stitched anti-fray edges', 'Natural rubber non-slip base', 'Machine washable'],
    specs: { Size: '900 x 400 mm', Thickness: '4 mm', Surface: 'Micro-weave cloth', Base: 'Natural rubber', Care: 'Machine washable' },
    tags: ['deskmat', 'mousepad', 'desk-setup'],
  },
  {
    sku: 'NX-LAP-DK9',
    images: ['https://images.unsplash.com/photo-1629317443274-7419b5dfb750?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1556196148-1fb724238998?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Link 9 Dock', category: 'Laptop Accessories', colorway: '#3F4A5A',
    tagline: '9-in-1 USB-C dock with dual 4K output',
    price: 6999, compareAtPrice: 8499, cost: 3200, stock: 44, rating: 4.5, unitsSold: 356, isFeatured: true,
    description: 'Nine ports from a single USB-C cable: two 4K60 displays, gigabit ethernet, an SD reader and 100W pass-through charging. The aluminium shell doubles as a heatsink so it stays cool under sustained transfer.',
    highlights: ['Dual 4K60 via HDMI + DisplayPort', '100W power delivery pass-through', 'Gigabit ethernet and SD/microSD', 'Aluminium body, passive cooling'],
    specs: { Ports: '9', Display: 'Dual 4K @ 60Hz', Power: '100W PD pass-through', Data: 'USB 3.2 Gen 2, 10Gbps', Material: 'Aluminium' },
    tags: ['dock', 'usb-c', 'workstation'],
  },
  {
    sku: 'NX-LAP-ST4',
    images: ['https://images.unsplash.com/photo-1612858249937-1cc0852093dd?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1589578228447-e1a4e481c6c8?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Riser Aluminium Stand', category: 'Laptop Accessories', colorway: '#94A3B8',
    tagline: 'Adjustable laptop stand, 11" to 17"',
    price: 2499, compareAtPrice: 3299, cost: 1000, stock: 92, rating: 4.7, unitsSold: 671,
    description: 'Milled from a single aluminium billet with silicone pads that grip without marking. Six height positions lift the screen to eye level, and the open frame keeps the laptop intake clear.',
    highlights: ['Six height positions', 'Fits 11" to 17" laptops', 'Silicone contact pads', 'Open frame for airflow'],
    specs: { Material: 'Anodised aluminium', 'Load capacity': '8 kg', Compatibility: '11" – 17"', Weight: '1.1 kg', Finish: 'Space grey' },
    tags: ['stand', 'ergonomics', 'desk-setup'],
  },
  {
    sku: 'NX-LAP-SS2',
    images: ['https://images.unsplash.com/photo-1676315487574-0d456abe4e1e?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1631749352438-7d576312185d?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Vault 1TB SSD', category: 'Laptop Accessories', colorway: '#155E75',
    tagline: 'Portable NVMe SSD, 1050MB/s',
    price: 8499, compareAtPrice: 9999, cost: 4600, stock: 31, rating: 4.8, unitsSold: 244,
    description: 'A pocket NVMe drive that sustains 1050MB/s reads without thermal throttling, wrapped in a shock-resistant shell rated for a two-metre drop. Hardware AES-256 encryption is handled on the drive.',
    highlights: ['1050MB/s read, 1000MB/s write', 'Hardware AES-256 encryption', '2m drop resistance, IP55', 'USB-C 3.2 Gen 2, works with phones'],
    specs: { Capacity: '1 TB', Read: '1050 MB/s', Write: '1000 MB/s', Interface: 'USB-C 3.2 Gen 2', Encryption: 'AES-256 hardware' },
    tags: ['ssd', 'storage', 'portable'],
  },
  {
    sku: 'NX-LAP-HB3',
    images: ['https://images.unsplash.com/photo-1625130694338-4110ba634e59?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1602025882379-e01cf08baa51?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Slim Hub 7', category: 'Laptop Accessories', colorway: '#525B6B',
    tagline: '7-port travel hub with 4K HDMI',
    price: 2999, cost: 1200, stock: 7, rating: 4.2, unitsSold: 398,
    description: 'The hub that lives in a laptop sleeve. Seven ports including 4K30 HDMI and 85W pass-through in a 62g aluminium body with a captive braided cable that cannot get lost.',
    highlights: ['Seven ports in a 62g body', '4K30 HDMI output', '85W power delivery pass-through', 'Captive braided cable'],
    specs: { Ports: '7', Weight: '62 g', Display: '4K @ 30Hz', Power: '85W PD', Data: 'USB 3.0, 5Gbps' },
    tags: ['hub', 'travel', 'usb-c'],
  },
  {
    sku: 'NX-MOB-PB2',
    images: ['https://images.unsplash.com/photo-1660491083562-d91a64d6ea9c?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Volt 20K Power Bank', category: 'Mobile Accessories', colorway: '#B45309',
    tagline: '20,000mAh, 65W USB-C PD',
    price: 3999, compareAtPrice: 4999, cost: 1750, stock: 58, rating: 4.6, unitsSold: 723,
    description: 'Enough capacity for three phone charges or one laptop top-up, at 65W through USB-C PD. A small LCD shows exact remaining percentage instead of four ambiguous dots.',
    highlights: ['20,000mAh, airline carry-on safe', '65W USB-C PD, charges laptops', 'LCD percentage readout', 'Charges three devices at once'],
    specs: { Capacity: '20,000 mAh', Output: '65W USB-C PD', Ports: '2x USB-C, 1x USB-A', Recharge: '1.8 hours', Weight: '412 g' },
    tags: ['power-bank', 'charging', 'travel'],
  },
  {
    sku: 'NX-MOB-CH3',
    images: ['https://images.unsplash.com/photo-1613141412501-9012977f1969?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1629121291243-7b5e885cce9b?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Volt GaN 65W Charger', category: 'Mobile Accessories', colorway: '#0E7490',
    tagline: 'Three-port GaN wall charger',
    price: 2799, compareAtPrice: 3499, cost: 1150, stock: 77, rating: 4.7, unitsSold: 587,
    description: 'GaN internals shrink a 65W three-port charger to roughly the footprint of a matchbox. Intelligent distribution gives the laptop what it needs and splits the rest between the phone and earbuds.',
    highlights: ['65W across three ports', 'GaN III, 40% smaller than silicon', 'Foldable pins for travel', 'Charges laptop, phone and buds together'],
    specs: { Output: '65W total', Ports: '2x USB-C, 1x USB-A', Technology: 'GaN III', Size: '58 x 52 x 30 mm', Safety: 'Over-current, over-temperature' },
    tags: ['charger', 'gan', 'fast-charging'],
  },
  {
    sku: 'NX-MOB-MG1',
    images: ['https://images.unsplash.com/photo-1658070429465-848c0796abf3?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?auto=format&fit=crop&w=900&q=70'], name: 'Nexora MagSnap Stand', category: 'Mobile Accessories', colorway: '#9333EA',
    tagline: 'Magnetic 15W wireless charging stand',
    price: 2199, cost: 880, stock: 66, rating: 4.3, unitsSold: 341,
    description: 'A weighted magnetic stand that holds a phone at any angle for calls or a kitchen recipe, charging at 15W while it does. The aluminium base stays put when you pull the phone off one-handed.',
    highlights: ['15W magnetic wireless charging', 'Adjustable viewing angle', 'Weighted base for one-hand removal', 'Case-friendly up to 3mm'],
    specs: { Output: '15W magnetic', Compatibility: 'MagSafe-compatible phones', Material: 'Aluminium + silicone', Cable: '1.5m USB-C', Weight: '340 g' },
    tags: ['wireless-charging', 'stand', 'magsafe'],
  },
  {
    sku: 'NX-MOB-CB4',
    images: ['https://images.unsplash.com/photo-1636858507939-acc6b17bda52?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Braided USB-C Cable 2m', category: 'Mobile Accessories', colorway: '#374151',
    tagline: '240W braided cable with 40Gbps data',
    price: 1299, compareAtPrice: 1699, cost: 430, stock: 0, rating: 4.5, unitsSold: 946,
    description: 'Rated for 240W charging and 40Gbps transfer, with an aramid-reinforced core tested to 30,000 bends. It drives an 8K display and charges a laptop over the same two metres.',
    highlights: ['240W charging, 40Gbps data', '8K60 display output', '30,000-bend tested', 'Aramid fibre core, braided nylon'],
    specs: { Length: '2 m', Power: '240W (48V/5A)', Data: '40 Gbps (USB4)', Video: '8K @ 60Hz', Durability: '30,000 bends' },
    tags: ['cable', 'usb-c', 'usb4'],
  },
  {
    sku: 'NX-MOB-GB1',
    images: ['https://images.unsplash.com/photo-1613141411244-0e4ac259d217?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1555532538-dcdbd01d373d?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Gimbal Grip', category: 'Mobile Accessories', colorway: '#1D4ED8',
    tagline: '3-axis phone gimbal, 12-hour battery',
    price: 8999, compareAtPrice: 10999, cost: 4400, stock: 15, rating: 4.4, unitsSold: 128,
    description: 'Three-axis stabilisation that folds into a jacket pocket. Subject tracking holds a face through a crowd, and the built-in extension rod plus tripod foot covers vlogging without extra kit.',
    highlights: ['3-axis stabilisation, 12h battery', 'AI subject tracking', 'Built-in extension rod and tripod', 'Folds to 180mm'],
    specs: { Axes: '3', Battery: '12 hours', 'Payload': '110 – 300 g', 'Folded size': '180 x 74 x 44 mm', Weight: '365 g' },
    tags: ['gimbal', 'video', 'creator'],
  },
  {
    sku: 'NX-AUD-SB1',
    images: ['https://images.unsplash.com/photo-1624978960600-7038b0d44d32?auto=format&fit=crop&w=900&q=70', 'https://images.unsplash.com/photo-1658927420074-85930da203ec?auto=format&fit=crop&w=900&q=70'], name: 'Nexora Sonar Mini', category: 'Audio', colorway: '#CA8A04',
    tagline: 'Pocket 12W speaker with a carabiner',
    price: 2499, compareAtPrice: 2999, cost: 950, stock: 5, rating: 4.2, unitsSold: 512,
    description: 'Clips to a backpack and runs 12 hours. Twelve watts is enough for a campsite or a balcony, and IPX7 means rain is not a reason to pack it away.',
    highlights: ['12W output in a 280g body', 'IPX7 waterproof', '12-hour battery', 'Integrated carabiner clip'],
    specs: { Output: '12W', Battery: '12 hours', Protection: 'IPX7', Connectivity: 'Bluetooth 5.2', Weight: '280 g' },
    tags: ['speaker', 'portable', 'outdoor'],
  },
];
